# -*- coding: utf-8 -*-
"""Caderno de exploração.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/FabioDGameiro/dataScience/blob/main/Caderno_de_explora%C3%A7%C3%A3o.ipynb

Caderno de exploração
"""
engine='python'
import pandas as pd

dados = pd.read_csv("../data/A151346189_28_143_208.csv",encoding="ISO-8859-1",skiprows=3, sep=";", skipfooter=12,thousands=".",decimal=",")
dados.head()

dados.tail()

dados.mean()

dados.info()

pd.options.display.float_format="{:.2f}".format
dados.head()

dados.mean()

dados["2008/Ago"]

dados["2008/Ago"].mean()

dados[["Unidade da Federação", "2008/Ago"]]

dados.plot(x="Unidade da Federação", y="2008/Ago")

dados.plot(x="Unidade da Federação", y="2008/Ago", kind="bar")

dados.plot(x="Unidade da Federação", y="2008/Ago", kind="bar", figsize=(9,6))

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
 
ax = dados.plot(x="Unidade da Federação", y="2008/Ago", kind="bar", figsize=(9,6))
ax.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"))
plt.title("UF X valor - 2008/Ago")
plt.show()

dados["2020/Ago"] = pd.to_numeric(dados["2020/Ago"],errors='coerce')
print(dados["2020/Ago"].dtypes)

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

dados["2020/Ago"] = pd.to_numeric(dados["2020/Ago"],errors='coerce')
ax202008 = dados.plot(x="Unidade da Federação", y="2020/Ago", kind="bar", figsize=(9,6))
ax202008.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"))
plt.title("UF X valor - 2020/Ago")
plt.show()